version: "3.4"
name: "biseo"

services:
  web:
    container_name: biseo-web
    restart: always
    build:
      context: .
      dockerfile: .docker/web.Dockerfile
    ports:
      - "${EXPOSE_PORT:?}:80"
    environment:
      - SERVER_URI="http://api:8000"
    depends_on:
      - api
    networks:
      - frontend
  api:
    container_name: biseo-api
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8000
      - DATABASE_URL=mysql://root:${DB_PASSWORD:?}@db:3306/${DB_NAME:?}
      - SECRET_KEY=${SECRET_KEY:?}
    build:
      context: .
      dockerfile: .docker/api.Dockerfile
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    container_name: biseo-db
    restart: always
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:?}
      - MYSQL_DATABASE=${DB_NAME:?}
    volumes:
      - biseo-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - backend

volumes:
  biseo-data:
    external: true

networks:
  frontend:
  backend:
