name: "biseo"

services:
  web:
    container_name: biseo-web
    image: ghcr.io/sparcs-kaist/biseo-web:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    ports:
      - "${EXPOSE_PORT:?}:80"
    environment:
      - SERVER_URI="http://api:8000"
    depends_on:
      - api
    networks:
      - frontend

  api:
    container_name: biseo-api
    image: ghcr.io/sparcs-kaist/biseo-api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8000
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - GOOGLE_CLIENT=${GOOGLE_CLIENT}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
    networks:
      - frontend
      - backend

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true

networks:
  frontend:
  backend:
