version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "${SSH_PORT:?err}:22"
      - "${API_PORT:?err}:3000"
      - "${WEB_PORT:?err}:5173"
    tty: true
    depends_on:
      - db
      - redis
    volumes:
      - root:/root
      - .:/usr/src

  db:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:?err}
      - MYSQL_DATABASE=${DB_NAME:?err}
    volumes:
      - db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data

volumes:
  root:
  db:
  redis:
