version: "3.4"
name: "biseo"

services:
  client:
    container_name: biseo-client
    restart: always
    build:
      context: .
      dockerfile: .docker/client.Dockerfile
    ports:
      - "${EXPOSE_PORT:?}:80"
    environment:
      - SERVER_URI="http://server:8000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - server
  server:
    container_name: biseo-server
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8000
      - DATABASE_URL=mysql://root:${DB_PASSWORD:?}@db:3306/${DB_NAME:?}
      - SECRET_KEY=${SECRET_KEY:?}
    build:
      context: .
      dockerfile: .docker/server.Dockerfile
    depends_on:
      - db
  db:
    container_name: biseo-db
    restart: always
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:?}
      - MYSQL_DATABASE=${DB_NAME:?}
    volumes:
      - biseo-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  biseo-data:
    external: true
