version: "3.9"
name: "biseo"

services:
  web:
    container_name: biseo-web
    image: ghcr.io/sparcs-kaist/biseo-web:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    ports:
      - "${EXPOSE_PORT:?}:80"
    environment:
      - SERVER_URI="http://api:8000"
    depends_on:
      - api
    networks:
      - frontend

  api:
    container_name: biseo-api
    image: ghcr.io/sparcs-kaist/biseo-api:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8000
      - DATABASE_URL=mysql://root:${DB_PASSWORD}@db:3306/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - frontend
      - backend

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - biseo-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - backend
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD $$MYSQL_DATABASE -e 'select 1'"
      interval: 1s
      retries: 3

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true

volumes:
  biseo-data:
    external: true

networks:
  frontend:
  backend:
