apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: biseo-db
  labels:
    app: biseo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biseo-db
  template:
    metadata:
      labels:
        app: biseo-db
    spec:
      containers:
      - name: biseo-db
        image: mysql:8.0
        args: 
          - --character-set-server=utf8mb4
          - --collation-server=utf8mb4_unicode_ci
          - --default_authentication_plugin=mysql_native_password
        ports:
        - containerPort: 3306
          name: db-port
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: biseo-secret
              key: DB_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: biseo-secret
              key: DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: biseo-env
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: biseo-env
              key: DB_USER
        - name: MYSQL_ROOT_HOST
          valueFrom:
            configMapKeyRef:
              name: biseo-env
              key: DB_ROOT_HOST
        volumeMounts:
          - name: biseo-db-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: biseo-db-storage
          persistentVolumeClaim:
            claimName: biseo-db-pv-claim