version: "3"

services:
  db:
    image: mysql:8.0
    container_name: biseo-dev-db
    ports:
      - "${DB_PORT:?err}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:?err}
      - MYSQL_DATABASE=${DB_NAME:?err}
    volumes:
      - db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: "mysql -uroot -p$$MYSQL_ROOT_PASSWORD $$MYSQL_DATABASE -e 'select 1'"
      start_period: 0s
      interval: 1s
      retries: 30

volumes:
  db:
