name: Deploy to Prod
permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
    name: Deploy Latest Dev to Prod

jobs:
  deploy-dev:
    name: Add Prod Tag to Dev
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - image: ghcr.io/sparcs-kaist/biseo-web
          - image: ghcr.io/sparcs-kaist/biseo-api

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest dev image
        run: docker pull ${{ matrix.image }}:dev

      - name: Tag image as prod
        run: docker tag ${{ matrix.image }}:dev ${{ matrix.image }}:prod

      - name: Push prod tag
        run: docker push ${{ matrix.image }}:prod
